config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("fitting/", include("fittings.urls", namespace="fittings")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fittings/urls.py
from django.urls import path
from . import views

app_name = "fittings"

urlpatterns = [
    path("", views.FittingInit.as_view(), name="init"),
    path("fitting", views.FittingCreate.as_view(), name="fitting"),
    path("finish", views.FittingFinish.as_view(), name="finish"),
    path("certi1", views.FittingCerti1.as_view(), name="certi1"),
    path("certi2", views.FittingCerti2.as_view(), name="certi2"),
    path("opt", views.FittingOpt.as_view(), name="opt"),
    path("opt_list", views.FittingOptList.as_view(), name="opt_list"),
]

core/models.py
from django.db import models


class TimeStampedModel(models.Model):

    """ Time Stamp Model """

    created = models.DateTimeField(auto_now_add=True)
    udpated = models.DateTimeField(auto_now=True)

    # DB에 등록되지 않는 모델
    class Meta:
        abstract = True

fittings/models.py
from django.db import models
import datetime
from core import models as core_models


class Fitting(core_models.TimeStampedModel):
    def front_image_path(self, filename):
        dirname = "fitting/%Y/%m/%d/{}_{}/{}".format(
            self.kid_name, self.parent_name, filename,
        )
        dirname = datetime.datetime.now().strftime(str(dirname))
        return dirname

    """ Abstract Item Model """

    user_key = models.AutoField(primary_key=True)
    kid_name = models.CharField(max_length=200, verbose_name="아동이름")
    parent_name = models.CharField(max_length=200, verbose_name="법정대리인 이름")
    location = models.CharField(max_length=200, verbose_name="거주지")
    birthdate = models.DateField(verbose_name="생년월일")
    phone_number = models.CharField(max_length=200, verbose_name="연락처")
    height = models.IntegerField(verbose_name="키")
    weight = models.IntegerField(verbose_name="몸무게")
    check1 = models.BooleanField(verbose_name="개인정보 수집 및 활용 동의")
    check2 = models.BooleanField(verbose_name="개인정보 수집 및 활용 동의2")
    chair_width = models.IntegerField(verbose_name="좌폭")
    back_height = models.IntegerField(verbose_name="등 높이")
    leg_length = models.IntegerField(verbose_name="다리 길이")
    seat_depth = models.IntegerField(verbose_name="좌석 깊이")
    front_picture = models.ImageField(upload_to=front_image_path, verbose_name="정면사진")
    side_picture = models.ImageField(upload_to=front_image_path, verbose_name="측면사진")

    def __str__(self):

        return str(self.created.date()) + "_" + self.kid_name + "_" + self.parent_name

fittings/forms.py
from django import forms
from .models import Fitting

YEARS = [x for x in range(1940, 2021)]


class MySelectDateWidget(forms.SelectDateWidget):
    def get_context(self, name, value, attrs):
        old_state = self.is_required
        self.is_required = False
        context = super(MySelectDateWidget, self).get_context(name, value, attrs)
        self.is_required = old_state
        return context


class FittingForm(forms.ModelForm):
    class Meta:
        model = Fitting
        fields = [
            "kid_name",
            "parent_name",
            "location",
            "birthdate",
            "phone_number",
            "height",
            "weight",
            "check1",
            "check2",
            "chair_width",
            "back_height",
            "leg_length",
            "seat_depth",
            "front_picture",
            "side_picture",
        ]
        widgets = {
            "kid_name": forms.TextInput(attrs={"placeholder": "예)홍길동"}),
            "parent_name": forms.TextInput(attrs={"placeholder": "예)홍길동"}),
            "location": forms.TextInput(attrs={"placeholder": "예)경기도 시흥시"}),
            "birthdate": MySelectDateWidget(years=YEARS, empty_label=("년도", "월", "일")),
            "phone_number": forms.TextInput(attrs={"placeholder": "예)010-1111-2222"}),
            "height": forms.TextInput(attrs={"maxlength": "3", "style": "width:30px;"}),
            "weight": forms.TextInput(attrs={"maxlength": "3", "style": "width:30px;"}),
            "check1": forms.CheckboxInput(),
            "check2": forms.CheckboxInput(),
            "chair_width": forms.TextInput(
                attrs={"maxlength": "3", "style": "width:30px;"}
            ),
            "back_height": forms.TextInput(
                attrs={"maxlength": "3", "style": "width:30px;"}
            ),
            "leg_length": forms.TextInput(
                attrs={"maxlength": "3", "style": "width:30px;"}
            ),
            "seat_depth": forms.TextInput(
                attrs={"maxlength": "3", "style": "width:30px;"}
            ),
            "front_picture": forms.FileInput(
                attrs={"onchange": "front_upload_img(this);"}
            ),
            "side_picture": forms.FileInput(
                attrs={"onchange": "side_upload_img(this);"}
            ),
        }
        error_messages = {
            "kid_name": {"required": "아동이름을 입력해주세요.",},
            "parent_name": {"required": "법정대리인을 입력해주세요.",},
            "location": {"required": "거주지를 입력해주세요.",},
            "birthdate": {"required": "생년월일을 입력해주세요.",},
            "phone_number": {"required": "연락처를 입력해주세요.",},
            "height": {"required": "아동의 키를 입력해주세요.",},
            "weight": {"required": "아동의 몸무게를 입력해주세요.",},
            "chair_width": {"required": "좌폭을 입력해주세요.",},
            "back_height": {"required": "등 높이를 입력해주세요.",},
            "leg_length": {"required": "다리 길이를 입력해주세요.",},
            "seat_depth": {"required": "좌석 깊이를 입력해주세요.",},
            "front_picture": {"required": "정면사진을 업로드해주세요.",},
            "side_picture": {"required": "측면사진을 업로드해주세요.",},
        }

    def clean_check1(self, *args, **kwargs):
        check1 = self.cleaned_data.get("check1")
        if check1 is False:
            raise forms.ValidationError("동의하셔야합니다.")
        return check1

    def clean_check2(self, *args, **kwargs):
        check2 = self.cleaned_data.get("check2")
        if check2 is False:
            raise forms.ValidationError("동의하셔야합니다.")
        return check2

core/views.py
from django.shortcuts import render

# Create your views here.

fittings/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import CreateView
from django.views.generic import TemplateView
from .forms import FittingForm


class FittingInit(TemplateView):
    template_name = "fittings/init.html"


class FittingFinish(TemplateView):
    template_name = "fittings/finish.html"


class FittingCerti1(TemplateView):
    template_name = "certi/certi1.html"


class FittingCerti2(TemplateView):
    template_name = "certi/certi2.html"

class FittingOpt(TemplateView):
    template_name = "fittings/opt.html"

class FittingOptList(TemplateView):
    template_name = "fittings/opt_list.html"


class FittingCreate(CreateView):
    template_name = "fittings/fit.html"
    form_class = FittingForm
    success_url = "/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def post(self, request, *args, **kwargs):
        form = FittingForm(request.POST, request.FILES)
        if form.is_valid():
            fit = form.save(commit=False)
            # 동의 구했는지 확인
            # 연락처 폼 확인
            if fit.check1 is False:
                print("test")

            fit.save()
            print(reverse("fittings:finish"))
            return redirect(reverse("fittings:finish"))
        return render(request, "fittings/fit.html", {"form": form})

templates/certi/certi1.html
{% load static %}
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <title>Welcome TodoWorks</title>

        <style media="screen">
            body {
                background: rgb(255, 255, 255);
                color: rgba(0, 0, 0, 0.87);
                font-family: Roboto, Helvetica, Arial, sans-serif;
                margin: 30px;
                padding: 0;
                font-size: 14px;
            }

            h2 {
                color: #ffa100;
                font-weight: bold;
                font-size: 28px;
                margin: 0 0 8px;
            }

            h1 {
                font-size: 22px;
                font-weight: bold;
                color: rgba(0, 0, 0, 0.6);
                margin: 0 0 16px;
            }

            p {
                line-height: 140%;
                margin: 14px 0 24px;
                font-size: 14px;
            }

            a {
                display: block;
                text-align: center;
                background: #039be5;
                text-transform: uppercase;
                text-decoration: none;
                color: white;
                padding: 16px;
                border-radius: 4px;
            }

            table {
                border-top: 1px solid #999;
                border-left: 1px solid #999;
                border-collapse: collapse;
                font-size: 14px;
            }

            td {
                padding: 5px;
                border-right: 1px solid #999;
                border-bottom: 1px solid #999;
            }

            td.t_h {
                background: #ccc;
            }

        </style>
    </head>

    <body>

        <h1>개인정보 수집ㆍ이용ㆍ제공 동의서</h1>

        <p>
            토도웍스 주식회사는 맞춤형 수동 휠체어 또는 토도드라이브 및 관련 서비스의 제공을 위하여 아래와 같이 개인정보를 수집∙이용 및 제공하고자 합니다. 내용을 자세히 읽으신 후 동의 여부를 정하여
            주십시오.
        </p>


        □ 개인정보 수집∙이용 내역

        <Table>
            <tr>
                <td class="t_h">항목</td>
                <td>성명 및 나이</td>
            </tr>
            <tr>
                <td class="t_h">목적</td>
                <td>휠체어 또는 토도드라이브 관련 서비스 제공(상담, AS, 고지사항 전달 등), 학술 및 연구</td>
            </tr>
            <tr>
                <td class="t_h">보유기간</td>
                <td>수집일로부터 최대 [3]년</td>
            </tr>
        </table>

        <i>※ 위 개인정보의 수집∙이용에 대한 동의를 거부할 권리가 있습니다. 그러나 동의를 거부할 경우 원활한 서비스 제공에 제한을 받을 수 있습니다.</i>
        <p></p>
        □ 개인정보 제3자 제공 내역

        <Table>
            <tr>
                <td class="t_h">제공받는 자</td>
                <td>재단법인 행복나눔재단, 국립재활원</td>
            </tr>
            <tr>
                <td class="t_h">목적</td>
                <td>학술 및 연구</td>
            </tr>
            <tr>
                <td class="t_h">항목</td>
                <td>성명 및 나이</td>
            </tr>
            <tr>
                <td class="t_h">보유기간</td>
                <td>수집일로부터 최대 [3]년</td>
            </tr>
        </table>

        <i>※ 위 개인정보의 제3자 제공에 대한 동의를 거부할 권리가 있습니다. 그러나 동의를 거부할 경우 원활한 서비스 제공에 제한을 받을 수 있습니다.</i>

        <p></p>
        □ 민감정보 수집∙이용 내역
        <Table>
            <tr>
                <td class="t_h">항목</td>
                <td>장애유형 및 장애등급</td>
            </tr>
            <tr>
                <td class="t_h">목적</td>
                <td>휠체어 또는 토도드라이브 관련 서비스 제공, 홍보, 학술 및 연구</td>
            </tr>
            <tr>
                <td class="t_h">보유기간</td>
                <td>수집일로부터 최대 [3]년</td>
            </tr>
        </table>

        <i>※ 위 민감정보의 수집∙이용에 대한 동의를 거부할 권리가 있습니다. 그러나 동의를 거부할 경우 원활한 서비스 제공에 제한을 받을 수 있습니다.</i>



        <p></p>
        □ 민감정보 제3자 제공 내역
        <Table>
            <tr>
                <td class="t_h">제공받는 자</td>
                <td>재단법인 행복나눔재단, 국립재활원</td>
            </tr>
            <tr>
                <td class="t_h">목적</td>
                <td>휠체어 또는 토도드라이브 관련 서비스 제공, 홍보, 학술 및 연구</td>
            </tr>
            <tr>
                <td class="t_h">항목</td>
                <td>장애유형 및 장애등급</td>
            </tr>
            <tr>
                <td class="t_h">보유기간</td>
                <td>수집일로부터 최대 [3]년</td>
            </tr>
        </table>

        <i>※ 위 민감정보의 제3자 제공에 대한 동의를 거부할 권리가 있습니다. 그러나 동의를 거부할 경우 원활한 서비스 제공에 제한을 받을 수 있습니다.</i>




    </body>

</html>

templates/fittings/finish.html
{% load static %}
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <title>Welcome TodoWorks</title>

        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script type="text/javascript" src="{% static 'js/common.js' %}"></script>

        <style media="screen">
            body {
                background: #ECEFF1;
                color: rgba(0, 0, 0, 0.87);
                font-family: Roboto, Helvetica, Arial, sans-serif;
                margin: 0;
                padding: 0;
            }

            #message {
                background: white;
                max-width: 800px;
                margin: 100px auto 16px;
                padding: 32px 24px;
                border-radius: 3px;
            }

            #message h2 {
                color: #ffa100;
                font-weight: bold;
                font-size: 28px;
                margin: 0 0 8px;
            }

            #message h1 {
                font-size: 22px;
                font-weight: 300;
                color: rgba(0, 0, 0, 0.6);
                margin: 0 0 16px;
            }

            #message p {
                line-height: 140%;
                margin: 16px 0 24px;
                font-size: 16px;
            }

            #message a {
                display: block;
                text-align: center;
                background: #039be5;
                text-transform: uppercase;
                text-decoration: none;
                color: white;
                padding: 16px;
                border-radius: 4px;
            }

            #message,
            #message a {
                box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
            }

            .buttonArea {
                overflow: hidden;
                margin-top: 20px;
            }

            .buttonArea .buttonBox {
                float: left;
            }

            .inputbox {
                overflow: hidden;
            }

            .inputbox .div_fl {
                float: left;
                padding: 5px;
            }

            .div_fl.lbl {
                width: 90px;
                text-align: right;
                font-size: 16px;
            }

            .inputbox .div_fl label {
                margin: 5px;
                font-size: 18px;
            }

            .inputbox .div_fl input {
                border-style: ridge;
                font-size: 16px;
            }

            .moveBtn {
                background-color: #008CBA;
                border: none;
                color: white;
                font-size: 16px;
                width: 110px;
                margin: 5px;
                text-align: center;
                vertical-align: center;
            }

            .picbox {
                overflow: hidden;
                height: 50px;
                float: left;
                margin: 5px;
            }

            .picbox label {
                display: inline-block;
                padding: .5em .75em;
                font-size: inherit;
                line-height: normal;
                vertical-align: middle;
                cursor: pointer;
                border: 1px solid #ebebeb;
                border-bottom-color: #e2e2e2;
                border-radius: .25em;
                color: #fff;
                background-color: #337ab7;
                border-color: #2e6da4;
            }

            .picbox input[type="file"] {
                /* 파일 필드 숨기기 */
                position: absolute;
                width: 1px;
                height: 1px;
                padding: 0;
                margin: -1px;
                overflow: hidden;
                clip: rect(0, 0, 0, 0);
                border: 0;
            }

            #load {
                color: rgba(0, 0, 0, 0.4);
                text-align: center;
                font-size: 13px;
            }

            @media (max-width: 600px) {

                body,
                #message {
                    margin-top: 0;
                    background: white;
                    box-shadow: none;
                }

                body {
                    border-top: 16px solid #ffa100;
                }
            }

            @media (max-width: 360px) {
                .moveBtn {
                    width: 90px;
                }
            }

        </style>
    </head>

    <body>
        <div>
            <div id="message">
                <h2>셀프 피팅</h2>

                <div style="margin-top: 20px;">
                    <label>신청이 완료되었습니다.</label>
                </div>
                <p></p>

                <div style="align-items: center;">
                    <img src="{% static 'image/m6_r.jpeg' %}" style="width: 45%;" />
                    <img src="{% static 'image/m6_y.jpeg' %}" style="width: 45%;" />
                </div>
                <p></p>
                <div class="buttonBox">
                    <a class="videobutton opt_view" href="{% url 'fittings:opt_list' %}"
                        style="margin: 10px 50px; padding: 7px; background-color: darkslategrey;">휠체어
                        추가옵션 보기</a>
                </div>
            </div>
        </div>
    </body>

</html>

templates/fittings/init.html
{% load static %}
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <title>Welcome TodoWorks</title>

        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script type="text/javascript" src="{% static 'js/common.js' %}"></script>

        <style media="screen">
            body {
                background: #ECEFF1;
                color: rgba(0, 0, 0, 0.87);
                font-family: Roboto, Helvetica, Arial, sans-serif;
                margin: 0;
                padding: 0;
            }

            #message {
                background: white;
                max-width: 800px;
                margin: 100px auto 16px;
                padding: 32px 24px;
                border-radius: 3px;
            }

            #message h2 {
                color: #ffa100;
                font-weight: bold;
                font-size: 28px;
                margin: 0 0 8px;
            }

            #message h1 {
                font-size: 22px;
                font-weight: 300;
                color: rgba(0, 0, 0, 0.6);
                margin: 0 0 16px;
            }

            #message p {
                line-height: 140%;
                margin: 16px 0 24px;
                font-size: 16px;
            }

            #message a {
                display: block;
                text-align: center;
                background: #039be5;
                text-transform: uppercase;
                text-decoration: none;
                color: white;
                padding: 16px;
                border-radius: 4px;
            }

            #message,
            #message a {
                box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
            }

            .buttonArea {
                overflow: hidden;
                margin-top: 20px;
            }

            .buttonArea .buttonBox {
                float: left;
            }

            .inputbox {
                overflow: hidden;
            }

            .inputbox .div_fl {
                float: left;
                padding: 5px;
            }

            .div_fl.lbl {
                width: 90px;
                text-align: right;
                font-size: 16px;
            }

            .inputbox .div_fl label {
                margin: 5px;
                font-size: 18px;
            }

            .inputbox .div_fl input {
                border-style: ridge;
                font-size: 16px;
            }

            .moveBtn {
                background-color: #008CBA;
                border: none;
                color: white;
                font-size: 16px;
                width: 110px;
                margin: 5px;
                text-align: center;
                vertical-align: center;
            }

            .picbox {
                overflow: hidden;
                height: 50px;
                float: left;
                margin: 5px;
            }

            .picbox label {
                display: inline-block;
                padding: .5em .75em;
                font-size: inherit;
                line-height: normal;
                vertical-align: middle;
                cursor: pointer;
                border: 1px solid #ebebeb;
                border-bottom-color: #e2e2e2;
                border-radius: .25em;
                color: #fff;
                background-color: #337ab7;
                border-color: #2e6da4;
            }

            .picbox input[type="file"] {
                /* 파일 필드 숨기기 */
                position: absolute;
                width: 1px;
                height: 1px;
                padding: 0;
                margin: -1px;
                overflow: hidden;
                clip: rect(0, 0, 0, 0);
                border: 0;
            }

            #load {
                color: rgba(0, 0, 0, 0.4);
                text-align: center;
                font-size: 13px;
            }

            @media (max-width: 600px) {

                body,
                #message {
                    margin-top: 0;
                    background: white;
                    box-shadow: none;
                }

                body {
                    border-top: 16px solid #ffa100;
                }
            }

            @media (max-width: 360px) {
                .moveBtn {
                    width: 90px;
                }
            }

        </style>
    </head>

    <body>
        <div id="page1" class="page1">

            <div id="message">
                <h2>셀프 피팅</h2>
                <p>안녕하세요. 토도웍스입니다.<br />
                    코로나19 상황으로 인하여 휠체어 피팅을 위한 아동 직접 대면상담이 불가한 상황 입니다. 이에 토도웍스는 온라인 대면 상담으로 전환합니다.<br />
                    휠체어 제작의 기본 자료가 되는 아이들 신체 측정에 대한(피팅) 방법을 설명 드립니다. 피팅은 아이들에게 건강한 휠체어를 지급하기 위한 중요한 과정입니다. <br />
                    아래 동영상을 확인 하시고 측정 하셔서 해당란에 기입해 주시면 됩니다. 기입이 확인 되면 상담원이 전화를 드리고 세부 조정작업을 하게 됩니다.<br />
                    아이들을 직접 만나지 못해 아쉽습니다.<br />
                    하루빨리 상황이 종식 되기를 바랍니다.
                </p>

                <div class="buttonArea">
                    <div class="buttonBox"><a class="moveBtn"
                            onclick="window.open('https://www.sesang-file.com/project/project01');">세상파일은?</a></div>
                    <div class="buttonBox"><a class="goPage2 moveBtn" href="{% url 'fittings:fitting' %}">시작하기</a></div>
                </div>
            </div>
        </div>

        <div>
            <br /><br />
        </div>
    </body>

</html>

templates/fittings/opt.html
{% load static %}
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <title>Welcome TodoWorks</title>

        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script type="text/javascript" src="{% static 'js/common.js' %}"></script>

        <style media="screen">
            body {
                background: #ECEFF1;
                color: rgba(0, 0, 0, 0.87);
                font-family: Roboto, Helvetica, Arial, sans-serif;
                margin: 0;
                padding: 0;
            }

            #message {
                background: white;
                max-width: 800px;
                margin: 100px auto 16px;
                padding: 32px 24px;
                border-radius: 3px;
            }

            #message h2 {
                color: #ffa100;
                font-weight: bold;
                font-size: 28px;
                margin: 0 0 8px;
            }

            #message h1 {
                font-size: 22px;
                font-weight: 300;
                color: rgba(0, 0, 0, 0.6);
                margin: 0 0 16px;
            }

            #message p {
                line-height: 140%;
                margin: 16px 0 24px;
                font-size: 16px;
            }

            #message a {
                display: block;
                text-align: center;
                background: #039be5;
                text-transform: uppercase;
                text-decoration: none;
                color: white;
                padding: 16px;
                border-radius: 4px;
            }

            #message,
            #message a {
                box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
            }

            .buttonArea {
                overflow: hidden;
                margin-top: 20px;
            }

            .buttonArea .buttonBox {
                float: left;
            }

            .inputbox {
                overflow: hidden;
            }

            .inputbox .div_fl {
                float: left;
                padding: 5px;
            }

            .div_fl.lbl {
                width: 90px;
                text-align: right;
                font-size: 16px;
            }

            .inputbox .div_fl label {
                margin: 5px;
                font-size: 18px;
            }

            .inputbox .div_fl input {
                border-style: ridge;
                font-size: 16px;
            }

            .moveBtn {
                background-color: #008CBA;
                border: none;
                color: white;
                font-size: 16px;
                width: 110px;
                margin: 5px;
                text-align: center;
                vertical-align: center;
            }

            .picbox {
                overflow: hidden;
                height: 50px;
                float: left;
                margin: 5px;
            }

            .picbox label {
                display: inline-block;
                padding: .5em .75em;
                font-size: inherit;
                line-height: normal;
                vertical-align: middle;
                cursor: pointer;
                border: 1px solid #ebebeb;
                border-bottom-color: #e2e2e2;
                border-radius: .25em;
                color: #fff;
                background-color: #337ab7;
                border-color: #2e6da4;
            }

            .picbox input[type="file"] {
                /* 파일 필드 숨기기 */
                position: absolute;
                width: 1px;
                height: 1px;
                padding: 0;
                margin: -1px;
                overflow: hidden;
                clip: rect(0, 0, 0, 0);
                border: 0;
            }

            #load {
                color: rgba(0, 0, 0, 0.4);
                text-align: center;
                font-size: 13px;
            }

            @media (max-width: 600px) {

                body,
                #message {
                    margin-top: 0;
                    background: white;
                    box-shadow: none;
                }

                body {
                    border-top: 16px solid #ffa100;
                }
            }

            @media (max-width: 360px) {
                .moveBtn {
                    width: 90px;
                }
            }

        </style>
    </head>

    <body>
        <div>
            <div id="message">
                <h2>셀프 피팅</h2>
                <p></p>

                <div style="align-items: center;">
                    <img src="{% static 'image/m6_r.jpeg' %}" style="width: 45%;" />
                    <img src="{% static 'image/m6_y.jpeg' %}" style="width: 45%;" />
                </div>
                <p></p>
                <div class="buttonBox">
                    <a class="videobutton opt_view" href="{% url 'fittings:opt_list' %}"
                        style="margin: 10px 50px; padding: 7px; background-color: darkslategrey;">휠체어
                        추가옵션 보기</a>
                </div>
            </div>
        </div>
    </body>

</html>